//
//  main.c
//  2
//
//  Created by Colin Wheeler on 5/8/12.
//  Copyright (c) 2012. All rights reserved.
//

/* 
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

int main(int argc, const char * argv[])
{	
	int numbers[2] = { 1, 2 };
	int sum = 0;
	do {
		if (numbers[1] % 2 == 0) {
			sum += numbers[1];
		}
		int total = numbers[0] + numbers[1];
		numbers[0] = numbers[1];
		numbers[1] = total;
	} while (numbers[1] <= 4000000);
	
	printf("total is %i",sum);
	
    return 0;
}

